### PR TITLE
Fix up a bunch of small things in the front-end

### PR DESCRIPTION
**Pull request by drewm1980**
I still have not successfully run gipuma, but these are a bunch of minor changes I have made while trying.  

The most important changes are the ones adding error checking, fixing the gpu version checking logic, and fixing up some wrong/misleading output messages.

As I said, I haven't gotten the code to fully run yet, so please test it on your rig!

Note that if you want view selection in this version, it needs to be explicitly enabled; see commit messages.

### CODE REVIEW

**Comment by drewm1980** [comment]
Temporarily closed since I think I may have introduced a segfault in 	6f0c890

**Comment by kysucix** [comment]
Hi drewm1980, thanks for the patch! if you fix the segfault I'm glad to accept the pull request.

**Comment by drewm1980** [comment]
Thanks for being open to contributions, but unfortunately I don't have the combination of gpus installed for working on gipuma anymore, or budget to keep working on it in the short term. I still suspect that some of the segfaults other users were running into were caused by some of the front-end and gpu selection issues I fixed up; it was possible for bad data to make it all the way to the gpu before due to some missing error checking. 

You might want to remove the thing where you do gpu memory management in the new constructor; it's probably easier to read/modify/debug/profile if the cpu <-> gpu transfers are made explicit, and it's not canonical C++ style (RAII) either. I reverted my (broken) attempted conversion to RAII. It's quite possible my branch works on your gpu and the issue I was running into was gpu architecture related. 

I bought a new gpu for this project, but I chose the fastest passively cooled gpu, which still meets the posted gipuma requirements, but is a generation or two behind the bleeding edge. It would be useful to post on the wiki which GPU's are reported to work with gipuma, and what environment you personally do development on.

**Comment by kysucix** [comment]
thanks I'll have a look. I'll update the wiki. My environment is ubuntu 14.04 with nvidia gtx 980

**Comment by ORNis** [comment]
Ubuntu 14.04 NV quadro K4000. 
- Tested on personal datasets (with oriented with @openMVG and converted to PMVS format)
- Very good results but resolution of images was bound to my "low" GPU memory (I cannot do more than approx. 0.20 the original resolution of my images)

- I think my CPU could be significantly faster than my GPU in such application (12 cores - 24 threads) and I have also 64Go RAM so I think #13 is an interesting question.

**Comment by kysucix** [comment]
Hi Romain,

I'm glad you could obtain good results.

It would be for sure an interesting comparison to see how the cpu version compares. We had a row-wise and columns-wise propagation of this algorithm running on cpu and it was much slower.

**Comment by kysucix** [comment]
I cherry picked your patches and add them to the project. What's left out if the RAII patch + the view selection logic which has to be true by default and some other consequent one on main.cpp giving conflict. Thanks!

**Comment by kysucix** [comment]
I suppose I close this pull request by now. Open a new one if needed. :)

**Pull request closed without merging**
